p4 barA.py
p4 barB.py
p4 circle.py
p4 hyperbolas.py
p4 line.py
p4 lineAndBar_better.py
p4 lineAndBar_good.py
p4 lineAndBar_ugly.py
p4 linesInPlot.py
p4 noFrame.py
p4 plotArray.py
p4 plotArrayB.py
p4 plotMarks.py
p4 regression.py
p4 scatter.py
p4 scatterB.py
p4 spiral.py
p4 styles.py
p4 textInPlot.py
p4 twoBarsA.py
p4 twoBarsB.py
p4 xyText.py
