python3 anchors.py
#python3 big.py
python3 bunnies.py
python3 rawcode.py
python3 fontWeight.py
python3 gramInGram.py
python3 helloWorld.py
python3 line.py
python3 rect.py
python3 rotatedText.py
python3 size.py
python3 style.py
#python3 style_getDefString.py
p4 textHowBig.py
python3 textVerticalAlignment.py
python3 unusualText.py
#python3 worksAndDoesNotWork.py
python3 wrapped.py
